trigger:
  - develop

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: build_and_deploy
    displayName: Build and Deploy
    dependsOn: []
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - job: build_and_deploy
        displayName: Build Docker images and deploy through Kubernetes
        steps:
          - script: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/
            displayName: Install Skaffold
          - task: DownloadSecureFile@1
            name: authkey
            displayName: "Download Service Account Key"
            inputs:
              secureFile: zk-gaming-azure.json
              retryCount: "2"
          - script: gcloud auth activate-service-account zk-gaming-azure@web3-335312.iam.gserviceaccount.com --key-file=$(authkey.secureFilePath)
            displayName: Activate Service Account
          - script: gcloud --quiet auth configure-docker eu.gcr.io
            displayName: Configure Docker Account
          - task: Kubernetes@1
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceEndpoint: "gke-zk-gaming"
              namespace: "zk-gaming-tk-staging"
              command: "login"
          - script: |
              skaffold run --filename=skaffold.snarkos.yaml
            displayName: Build and push Aleo Docker images
            enabled: false
          - script: |
              skaffold run --filename=skaffold.staging.yaml
            displayName: Build and push Toolkit Docker images
