FROM node:18-bullseye as build

RUN apt update
RUN apt install -y git make g++ pkg-config openssl libssl-dev clang

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ENV PATH "$PATH:/root/.cargo/bin"

RUN rustup update

# installing Leo
RUN git clone https://github.com/AleoHQ/leo
# latest commit that works properly with our codebase
RUN cd leo && git checkout 1c05df35297089f07ab5f5ad24dc48b6a820695f
RUN cd leo && cargo install --path .

# installing SnarkOS
RUN git clone https://github.com/AleoHQ/snarkOS
# latest commit that works properly with our codebase
RUN cd snarkOS && git checkout 8ad729748ff07cc417341538f59504f602ec2cd8
RUN cd snarkOS && cargo install --path .

# downloading provers and verifiers
RUN mkdir -p /root/.aleo/resources/
ENV FILE_NAME mint.prover.11fa6f2
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME transfer.prover.837ad21
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME join.prover.369fac2
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME split.prover.8713930
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME fee.prover.0a31a56
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME mint.verifier.e1ae0c8
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME transfer.verifier.db46e4c
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME join.verifier.728e514
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME split.verifier.b6bb949
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME fee.verifier.2186739
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME inclusion.prover.b9921c5
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME inclusion.verifier.3f4d6b7
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME shifted-powers-of-beta-16.usrs.d99bcb3
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME powers-of-beta-16.usrs.84631bc
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME shifted-powers-of-beta-18.usrs.9a1859e
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME shifted-powers-of-beta-17.usrs.2025178
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME powers-of-beta-17.usrs.7c27308
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME powers-of-beta-18.usrs.7a12bcb
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME shifted-powers-of-beta-19.usrs.662e343
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME
ENV FILE_NAME powers-of-beta-19.usrs.e535d44
RUN curl https://testnet3.parameters.aleo.org/$FILE_NAME --output /root/.aleo/resources/$FILE_NAME

WORKDIR /usr/main/

COPY deployment/contracts/ deployment/contracts/

RUN cd deployment/contracts/ && cargo build --release
