apiVersion: skaffold/v3
kind: Config
metadata:
  name: zk-gaming-tk
build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
    push: true
  artifacts:
    - image: eu.gcr.io/web3-335312/aleo/zk-gaming-snarkos
      docker:
        dockerfile: Dockerfile.snarkos
