apiVersion: skaffold/v3
kind: Config
metadata:
  name: zk-gaming-tk
build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
  artifacts:
    - image: zk-gaming-snarkos
      docker:
        dockerfile: Dockerfile.snarkos
    - image: zk-gaming-tk
      requires:
        - image: zk-gaming-snarkos
          alias: ZK_GAMING_ALEO
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - ./deployment/local
deploy:
  kubectl: {}
