apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: zk-gaming-tk
build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
    push: true
  artifacts:
    - image: localhost:5000/aleo/zk-gaming-tk
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - ./deployment/local
    defaultNamespace: zk-gaming-tk-local
