@program
function throw_dice(public a: u32, b: u32) -> u32 {
    let c: u32 = a + b;
    return c;
}

@program
function random(public a: u32, b: u32) -> u32 {
    let c: u32 = a + b;
    return c;
}

@program
function generate_proof(public a: u32, b: u32) -> u32 {
    let c: u32 = a + b;
    return c;
}

@program
function powerups(public a: u32, b: u32) -> u32 {
    let c: u32 = a + b;
    return c;
}
