apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-gaming-tk
spec:
  selector:
    matchLabels:
      app: zk-gaming-tk
  template:
    metadata:
      labels:
        app: zk-gaming-tk
    spec:
      containers:
        - name: zk-gaming-tk
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 940m
              memory: 2048Mi
            limits:
              cpu: 940m
              memory: 4096Mi
          ports:
            - containerPort: 5001
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ZK_TK_NAME
              value: "ZK_TK"
