apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-gaming-tk
spec:
  selector:
    matchLabels:
      app: zk-gaming-tk
  template:
    spec:
      containers:
        - name: zk-gaming-tk
          imagePullPolicy: Always
          image: eu.gcr.io/web3-335312/aleo/zk-gaming-tk:latest
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CORS_ORIGINS
              value: https://backend.boloney.staging.kryha.dev,https://api.boloney.staging.kryha.dev,https://boloney.staging.kryha.dev,https://boloney.io
            - name: ZK_MODE
              value: snarkos_broadcast
            - name: BOLONEY_MATCH_VERSION
              value: SEDSUBST_BOLONEY_MATCH_VERSION
            - name: BOLONEY_MATCH_SUMMARY_VERSION
              value: SEDSUBST_BOLONEY_MATCH_SUMMARY_VERSION
            - name: DICE_VERSION
              value: SEDSUBST_DICE_VERSION
            - name: POWER_UP_VERSION
              value: SEDSUBST_POWER_UP_VERSION
            - name: POWER_UP_2_VERSION
              value: SEDSUBST_POWER_UP_2_VERSION
            - name: RNG_VERSION
              value: SEDSUBST_RNG_VERSION
            - name: HASH_CHAIN_VERSION
              value: SEDSUBST_HASH_CHAIN_VERSION
