apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-gaming-tk
spec:
  selector:
    matchLabels:
      app: zk-gaming-tk
  template:
    spec:
      containers:
        - name: zk-gaming-tk
          image: eu.gcr.io/web3-335312/aleo/zk-gaming-tk:latest
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CORS_ORIGINS
              value: https://backend.liars-dice.staging.kryha.dev
            - name: ZK_MODE
              value: snarkos_broadcast
