apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-gaming-tk
spec:
  selector:
    matchLabels:
      app: zk-gaming-tk
  template:
    spec:
      containers:
        - name: zk-gaming-tk
          image: zk-gaming-tk
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ZK_MODE
              value: testnet_public
